//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\BOARD_ALL_ALL\\OLD_Comps\\Specialist\\Sybr_FIFAN\\SYABR_SBORKA\\Переписка PVV\\GAMES" +
            "\\games_mx_i80\\")]
        public string pathIn {
            get {
                return ((string)(this["pathIn"]));
            }
            set {
                this["pathIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\BOARD_ALL_ALL\\OLD_Comps\\Specialist\\Sybr_FIFAN\\SYABR_SBORKA\\Переписка PVV\\GAMES" +
            "\\games_mx_i80\\1\\")]
        public string pathOut {
            get {
                return ((string)(this["pathOut"]));
            }
            set {
                this["pathOut"] = value;
            }
        }
    }
}
